### ISSUE TITLE
Matrix dimensions

### ISSUE THREAD

**Issue by fenilgmehta** [pratham16cse/cs725-2020-assign2#1]
Can you please make the dimensions of the numpy matrices passed as parameters and wherever possible more explicit just like it was done in assignment 1 instead of describing them in words such as rowwise, columnwise,... which is very confusing. This would ensure that the functions we write work the same when tested by us and you guys as well.

**Comment by pratham16cse** [comment]
Updated docstrings with input and output shapes in commit ce930a6fe85496b69d8c33741484e9f94b2af766.

Please note that structure of neural network parameters is not going to be specified by TAs unlike assignment 1 as backprop algorithm heavily depends on it and there are multiple ways to create neural network parameters and write backprop for them.
